### ISSUE TITLE
New testcase

### ISSUE THREAD

**Issue by psugihara** [BlackGlory/parse-favicon#27]
Hey, noticed this one does not work. TBH I can't figure out where the favicon is hiding: https://tripalink.com

Love your little lib btw!

**Comment by BlackGlory** [comment]
I can't reproduce this issue with [Favicon Detector](https://chromewebstore.google.com/detail/favicon-detector/jlfeffjhgmgblofcgpbgpkkhfniipejm):
![image](https://github.com/BlackGlory/parse-favicon/assets/1365962/c9a57f6f-76e0-437a-9371-fd7a815719b9)

**Comment by psugihara** [comment]
interesting. maybe i'm getting blocked by ip or something. Will check favicon detector next time, thanks!

**Comment by BlackGlory** [comment]
The most likely reason is that you didn't provide a `bufferFetcher`, the documentation is poorly written, sorry.

**Comment by psugihara** [comment]
Oh yep that does fix it. I took bufferFetcher out because it was so much quicker without. Unfortunately https://tripalink.com/ takes 18+ seconds  to resolve with bufferFetcher and I'm trying to find a way to do everything within a 10s function timeout.
